### ISSUE TITLE
Meetup API for events

### ISSUE THREAD

**Issue by MoribundMedium** [nashvillefcc/nashvillefcc2020website#24]
# Acceptance Criteria
When users access our Events page, they should be presented with a list of upcoming events pulled from the Meetup site's API. In this ticket, we want to invoke that API to access the events. It does not need to be rendered on the UI.

Note: The official Meetup API is limited to Meetup Pro users, which is not something the group is currently paying for. It's possible that we could pay for 1 month to get an API consumer account authorized, but we might be better off with free options instead. We could use a web scraper to periodically check and log the events for the group. There is also a possible Zapier integration we can take advantage of:
![image](https://user-images.githubusercontent.com/51807366/96626546-416e1700-12d5-11eb-9f76-798751fe8c61.png)

See this section of the Discord discussion for more details: https://discordapp.com/channels/542870629737824277/601382608277995520/758847898187333653

### Related Features
- #4 Old ticket for this issue

### Resources
- [Meetup API](https://secure.meetup.com/meetup_api)

**Comment by itzsaga** [comment]
So, we will not get a Pro account 😢. However, we can work around this! The easiest way, in my opinion, is to consume the RSS feed of our events and convert it to JSON. Since RSS is just XML conversion libraries are available. We can implement this in a Netlify Function and call the function from the site.

Info:
RSS Feed URI: https://www.meetup.com/freeCodeCamp-Nashville/events/rss/
Netlify Functions docs: https://docs.netlify.com/functions/overview/
RSS-to-JSON library: https://www.npmjs.com/package/rss-to-json

Of note you'll have to use `require` syntax. So, `var Feed = require('rss-to-json');`.
